### ISSUE TITLE
Add release number to important binder updates

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#22]
Hi @alimanfoo,

It seems that binder update requires a number of follow-up actions in the dependent repos: update within each repo, environment updates for multiple repo users, sometimes in multiple instances. Maybe we should post certain version of binder as a release to notify everyone that it is time to get an updated version installed?

**Comment by alimanfoo** [comment]
Hi @amakunin, sorry I didn't reply to this at the time. This is a very good idea. How about a `major.minor` versioning scheme where removing a package requires a major version bump but otherwise adding or upgrading packages requires only a minor version bump. Then use git tags like `v1.0` to mark a release, and create a corresponding [release](https://github.com/malariagen/binder/releases).

**Comment by alimanfoo** [comment]
I've tagged a [v1.0](https://github.com/malariagen/binder/releases/tag/v1.0) release, recommend upgrading repos that use malariagen/binder as a submodule. You can checkout a tag specifically, e.g.:

```
$ cd /path/to/parent/repo
$ git checkout master
$ git pull
$ git checkout -b upgrade-binder-v1.0
$ cd binder
$ git fetch
$ git checkout v1.0
$ cd ..
$ git add binder
$ git commit -m "upgrade binder to v1.0"
$ git push -u origin upgrade-binder-v1.0
```

...then make a PR (e.g., https://github.com/malariagen/vector-ops/pull/577).
